agent_count: 1
run_id: parsing_fork_C_exp5
log_path: /data/mchivuku/samantha_output/base_agents/small/${run_id}
#log_path: data/${run_id}
mode: test
train_eps: 1000
test_eps: 40
hydra.job.chdir: True
cuda: 0
experiment: parsing

defaults:
  - _self_
  - Agent: basic
  - Environment: parsing
  - hydra
