agent_count: 1
run_id: parsing_fork_C_lstm_small_exp1
log_path: /data/mchivuku/embodiedai/benchmark_experiments/${run_id}
#log_path: data/${run_id}
mode: full
train_eps: 1000
test_eps: 40
hydra.job.chdir: True
cuda: 0
experiment: parsing

defaults:
  - _self_
  - Agent: basic
  - Environment: parsing
  - hydra
