agent_count: 1
run_id: oneshot_small_front_ship_small_exp5
log_path: /data/mchivuku/embodiedai/benchmark_experiments/oneshot/base_agents/small/${run_id}
#log_path: data/${run_id}
mode: full
train_eps: 1000
test_eps: 40
hydra.job.chdir: True
cuda: 0
experiment: oneshot

defaults:
  - _self_
  - Agent: basic
  - Environment: oneshot
  - hydra
