agent_count: 1
run_id: parsing_vit_random_frozen_exp5
log_path: /data/mchivuku/embodiedai/benchmark_experiments/frozen_encoders/${run_id}
mode: full
train_eps: 10000
test_eps: 40
hydra.job.chdir: True
cuda: 0
experiment: parsing

defaults:
  - _self_
  - Agent: basic
  - Environment: parsing
  - hydra
