agent_count: 1
run_id: parsing_icm_lr_dp1_exp1
log_path: data/${run_id}
mode: full
train_eps: 1000
test_eps: 40
hydra.job.chdir: True
cuda: 0

defaults:
  - _self_
  - Agent: basic
  - Environment: basic
  - hydra
