agent_count: 1
run_id: viewinvariant_fork_front_exp5
log_path: /data/mchivuku/embodiedai/benchmark_experiments/viewinvariant/fork/${run_id}
#log_path: data/${run_id}
mode: full
train_eps: 1000
test_eps: 40
hydra.job.chdir: True
cuda: 0
experiment: viewpoint

defaults:
  - _self_
  - Agent: basic
  - Environment: viewpoint
  - hydra
