Brain:
  reward: unsupervised
  batch_size: 512
  buffer_size: 2048
  algorithm: PPO
  policy: CnnPolicy
  seed: 42
  encoder: large
  train_encoder: True
Body:
  type: basic
  dvs: False
Environment:
  # condition
  imprinting_condition: "ChickBiologicalMotion"
  test_condition: "Rest"
  target_video: "biomo.webm"
  nontarget_video: "Rest"
  # generic config
  executable_path: "/data/wjpeacoc/builds/biomotion.x86_64"
  record_chamber: False
  record_agent: False
  recording_frames: 100
Config:
  run_id: "biomotion-test1"
  num_brains: 1
  mode: "full"
  train_eps: 1
  test_eps: 1
  output_dir: "/data/wjpeacoc/experiments/results/biomotion/"
