Brain:
  reward: supervised
  batch_size: 512
  buffer_size: 2048
  algorithm: PPO
  policy: CnnPolicy
  seed: 42
  encoder: 
  train_encoder: True
Body:
  type: basic
  dvs: True
Environment:
  use_ship: True
  background: A
  executable_path: "/data/wjpeacoc/builds/parsing/ParsingBuild.x86-64"
  record_agent: False
  record_chamber: False
  recording_frames: 1000
Config:
  run_id: "parsing_trial"
  num_brains: 1
  mode: "full"
  train_eps: 10
  test_eps: 2
  output_dir: "/data/wjpeacoc/parsing_trial_data/"
