# Set env_path and video_dir.
env_dir: /home/denpak/pipeline_embodied/Executables/FixedEnvSeed
env: Rearing_Chamber
seed: 1
cuda: 0 # Set CUDA_VISIBLE_DEVICES.

# Config agents.
policy_encoder: resnet
intrinsic_reward_encoder: resnet

# Config training.
batch_size: 500
buffer_size: 5000
num_epoch: 3
epsilon: 0.2
beta: 1.0e-2
learning_rate: 1.0e-4
learning_rate_schedule: linear

defaults:
  - run_options: train # train or test
  - reward_signals: curiosity
  - trainer
  - engine_settings
  - hydra
