agent_count: 1
run_id: test_parsing_exp1
log_path: /data/mchivuku/embodiedai/benchmark_experiments/${run_id}
mode: train
train_eps: 1000
test_eps: 40
hydra.job.chdir: True
cuda: 0

defaults:
  - _self_
  - Agent: basic
  - Environment: parsing
  - hydra
