agent_count: 13
run_id: test_agent
log_path: &now_dir ../Data/${run_id} #${now:%Y-%m-%d}/${now:%H-%M-%S}
mode: full
train_eps: 1000
test_eps: 100
hydra.job.chdir: True
cuda: 0

defaults:
  - _self_
  - Agent: basic
  - Environment: basic
  - hydra
