agent_count: 13
log_path: &now_dir ../Data/${now:%Y-%m-%d}/${now:%H-%M-%S}
mode: full
run_id: test_agent
train_eps: 1000
test_eps: 100
hydra.job.chdir: True

defaults:
  - _self_
  - Agent: basic
  - Environment: basic
  - hydra
