agent_count: 2
run_id: ship_recording_backgroundA
log_path: Data/${run_id}
mode: train
train_eps: 1
test_eps: 40
hydra.job.chdir: True
cuda: 0

defaults:
  - _self_
  - Agent: basic
  - Environment: parsing
  - hydra
