env_settings:
  seed: ${seed}
  env_path: ${env_dir}/${env}
  base_port: 5000
  env_args:
    episode-steps: 5000
    num-agents: ${num_agents}
    fov: ${fov}
    log_dir: logs/test_${num_agents}
checkpoint_settings:
  run_id: test_${num_agents}
  initialize_from: train
  resume: false
  inference: false
