env_settings:
  seed: ${seed}
  env_path: ${env_dir}/${env}
  base_port: 5000
  env_args:
    imprint_video: /home/denpak/number/Circles.webm
    episode_steps: 1000
    log_dir: logs/train
    input_resolution: 96
    env_seed: 42
checkpoint_settings:
  run_id: train
  resume: false
  inference: false
