ChickAI:
  Environment:
    use_ship: false
    side_view: false
    base_port: 5000
    env_path: ../Env/rearing_chamber
 
  Agent:
    reward: supervised

  Experiment:
    agentCount: 13
    mode: full
    run_id: test_agent
    train_eps: 1000
    test_eps: 100
    log_path: ./Example/Logs/
